title: <p align="center"> Daniel Iglesias C. Melo </p>
logo: "/images/profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
   <p align="center">
  <a href="https://www.linkedin.com/in/daniel-iglesias-melo/">LinkedIn</a> |
  <a href="https://github.com/Melo97">GitHub</a>
  </p>
  
  <p align="justify">
  I am an Industrial Engineer specializing in Machine Learning & Analytics.
  <br><br>
  Scroll down to see my latest projects on the field
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
